version: "3"

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "docker"
        ports:
            - "5432:5432"
        volumes:
            - /home/felipe/databases/receitas:/var/lib/postgresql/data
# Database: postgres
